name: Desplegar la aplicación a producción
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Conectando por ssh y realizando el deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf prueba-ahc
            git clone https://github.com/Jesucristhorr/prueba-ahc.git
            cd prueba-ahc
            docker-compose up -d --build
